#!/usr/bin/env python
# s3-ls
import argparse
import os
import subprocess
import sys

parser = argparse.ArgumentParser(description='List S3 objects and common prefixes under a prefix or all S3 buckets.')
parser.add_argument('s3Uri', help='the s3 URI')
args = parser.parse_args()

COMMAND = ["aws", "s3", "ls", args.s3Uri]

if os.getenv("RD_CONFIG_RECURSIVE") == "true":
    COMMAND.append("--recursive")
if os.getenv("RD_CONFIG_HUMAN_READABLE") == "true":
    COMMAND.append("--human-readable")
if os.getenv("RD_CONFIG_SUMMARIZE") == "true":
    COMMAND.append("--summarize")
if "RD_CONFIG_PAGE_SIZE" in os.environ:
    COMMAND.append("--page-size")
    COMMAND.append(os.getenv("RD_CONFIG_PAGE_SIZE"))
if "RD_CONFIG_ENDPOINT_URL" in os.environ:
    COMMAND.append("--endpoint-url")
    COMMAND.append(os.getenv("RD_CONFIG_ENDPOINT_URL"))
if "RD_CONFIG_ACCESS_KEY" in os.environ:
    os.environ["AWS_ACCESS_KEY_ID"] = os.environ["RD_CONFIG_ACCESS_KEY"]
if "RD_CONFIG_SECRET_ACCESS_KEY" in os.environ:
    os.environ["AWS_SECRET_ACCESS_KEY"] = os.environ["RD_CONFIG_SECRET_ACCESS_KEY"]
if "RD_CONFIG_DEFAULT_REGION" in os.environ:
    os.environ["AWS_DEFAULT_REGION"] = os.environ["RD_CONFIG_DEFAULT_REGION"]

#print >>sys.stdout, "debug: COMMAND: ", COMMAND

try:
    retcode = subprocess.call(COMMAND)
    sys.exit(retcode)
except OSError as e:
    print >>sys.stderr, "Command error:", e
    sys.exit(1)
# Done
