#!/bin/bash
# s3-rm
set -eu

(( $# != 1 )) && {
   echo >&2 "usage: $0 S3Uri"
   exit 2
}


declare -r S3Uri=$1

declare -a CLOPTS=()

[[ "${RD_CONFIG_DRYRUN:-}" == true ]]           && CLOPTS+=(--dryrun)
[[ "${RD_CONFIG_QUIET:-}" == true ]]            && CLOPTS+=(--quiet)
[[ "${RD_CONFIG_RECURSIVE:-}" == true ]]        && CLOPTS+=(--recursive)
[[ "${RD_CONFIG_ONLY_SHOW_ERRORS:-}" == true ]] && CLOPTS+=(--only-show-errors)
[[ -n "${RD_CONFIG_PAGE_SIZE:-}" ]]             && CLOPTS+=(--page-size $RD_CONFIG_PAGE_SIZE)
[[ -n "${RD_CONFIG_INCLUDE:-}" ]]               && CLOPTS+=(--include $RD_CONFIG_INCLUDE)
[[ -n "${RD_CONFIG_EXCLUDE:-}" ]]               && CLOPTS+=(--exclude $RD_CONFIG_EXCLUDE)


[[ -n "${RD_CONFIG_ACCESS_KEY:-}" ]]        && export AWS_ACCESS_KEY_ID=${RD_CONFIG_ACCESS_KEY}
[[ -n "${RD_CONFIG_SECRET_ACCESS_KEY:-}" ]] && export AWS_SECRET_ACCESS_KEY=${RD_CONFIG_SECRET_ACCESS_KEY}
[[ -n "${RD_CONFIG_DEFAULT_REGION:-}" ]]    && export AWS_DEFAULT_REGION=${RD_CONFIG_DEFAULT_REGION}

aws s3 rm "$S3Uri" "${CLOPTS[@]:-}"


exit $?
# Done