name: CI Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fetch tags
        run: git fetch --tags --progress --no-recurse-submodules origin
        if: ${{ !contains(github.ref, 'refs/tags') }}
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        
      - name: Get release version
        id: get_version
        run: |
          VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: aws-s3-steps-${{ steps.get_version.outputs.VERSION }}
          path: build/libs/aws-s3-steps-${{ steps.get_version.outputs.VERSION }}.zip
          retention-days: 30